Description: deploys an RDS instance

Resources:
  RDSAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: RDSAccess
      GroupDescription: "Allows RDS Ingress from within the VPC"
      VpcId: !ImportValue VPC-VPC
      SecurityGroupIngress:
        - FromPort: 5432
          ToPort: 5432
          IpProtocol: tcp
          CidrIp: !ImportValue VPC-VPCCIDR

  RDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: postgres
      DBSubnetGroupName: !ImportValue VPC-PrivateSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSAccess

Outputs:
  Endpoint:
    Description: Endpoint
    Value: !GetAtt RDS.Endpoint.Address
