Transform: AWS::Serverless-2016-10-31

Description: 'Cognito resources'

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AutoVerifiedAttributes:
        - email
      DeletionProtection: INACTIVE
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: !Sub
          - 'edward@${EmailIdentity}'
          - EmailIdentity: !ImportValue ses-EmailIdentity
        SourceArn: !Sub
          - 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${EmailIdentity}'
          - EmailIdentity: !ImportValue ses-EmailIdentity
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - AttributeDataType: String
          Name: email
          Required: True
          DeveloperOnlyAttribute: False
          Mutable: True
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: True

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https://echo.edwardmurphy.net/oauth2/callback
      ReadAttributes:
        - email
      AllowedOAuthFlows:
        - code
        - implicit
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Select [2, !Split ['/', !Ref AWS::StackId]] # use stack id as random number
      UserPoolId: !Ref UserPool

  UserPoolAlias:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: edwardmurphy.net.
      Name: auth.echo.edwardmurphy.net.
      Type: A
      Weight: 100
      SetIdentifier: primary
      AliasTarget:
        DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  UserPoolClientId:
    Description: The ID of the UserPoolClient
    Value: !Ref UserPoolClient
