Description: SQS Queues
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      VisibilityTimeout: 120
      ContentBasedDeduplication: true

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      Role: !GetAtt LambdaRole.Arn
      Timeout: 120
      Code:
        ZipFile: |
          exports.handler = async function(event) {
            const wait = ( ms ) => new Promise( r => setTimeout( r, ms ) );
            const bodies = event.Records.map( record => record.body );
            console.log('start', bodies);
            await wait(10e3);
            console.log('stop', bodies);
            return {
              statusCode: 200,
              body: JSON.stringify('Hello from Lambda!'),
            };
          };

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !GetAtt Lambda.Arn

Outputs:
  TestFIFOEndpoint:
    Description: Queue URL
    Value: !GetAtt Queue.QueueUrl
