Transform: AWS::Serverless-2016-10-31

Description: fx quote lab

Parameters:
  StageName:
    Type: String
    Default: api

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  GetFxQuote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-fx-quote/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /quotes
            Method: POST

  CreatePayments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-payments/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 300
      Policies:
        - Statement:
            - Sid: DynampDB
              Effect: "Allow"
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:*:${AWS::AccountId}:table/*"
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /fx-payments
            Method: POST

  PaymentSQSBridge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: payment-sqs-bridge/
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 300
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: SQSSendMessage
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !Sub "arn:aws:sqs:*:${AWS::AccountId}:*"

  FxPaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fx-payments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: paymentId
          AttributeType: S
      KeySchema:
        - AttributeName: paymentId
          KeyType: HASH

  NewFxPaymentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NewFxPaymentQueue

Outputs:
  GetFxQuoteApi:
    Description: API Gateway endpoint URL for GetFxQuote function
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/quotes
