Transform: AWS::Serverless-2016-10-31

Description: fx quote lab

Parameters:
  StageName:
    Type: String
    Default: api

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  GetFxQuote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-fx-quote/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /quotes
            Method: POST

  CreatePayments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-payments/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 300
      Policies:
        - Statement:
            - Sid: DynampDB
              Effect: "Allow"
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:*:${AWS::AccountId}:table/*"
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /fx-payments
            Method: POST

  PaymentSQSBridge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: payment-sqs-bridge/
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 30
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: SQS
              Effect: Allow
              Action:
                - sqs:*
              Resource: !Sub "arn:aws:sqs:*:${AWS::AccountId}:*"
        - Statement:
          - Sid: DynamoDBStreamsPermissions
            Effect: Allow
            Action:
              - dynamodb:GetShardIterator
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:ListStreams
            Resource: "*"

  FxPaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fx-payments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: paymentId
          AttributeType: S
      KeySchema:
        - AttributeName: paymentId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  NewFxPaymentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NewFxPaymentQueue

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt FxPaymentsTable.StreamArn
      FunctionName: !GetAtt PaymentSQSBridge.Arn
      Enabled: True
      StartingPosition: LATEST

Outputs:
  GetFxQuoteApi:
    Description: API Gateway endpoint URL for GetFxQuote function
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/quotes
