Transform: AWS::Serverless-2016-10-31

Description: Provisions an SQS FIFO queue with a Lambda that processes items one at a time

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      VisibilityTimeout: 30
      ContentBasedDeduplication: true

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaRole.Arn
      ReservedConcurrentExecutions: 1
      Timeout: 30

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !GetAtt Lambda.Arn
      # ScalingConfig:
      #   MaximumConcurrency: 2

Outputs:
  TestFIFOEndpoint:
    Description: Queue URL
    Value: !GetAtt Queue.QueueUrl
