Description: Deploys instances

Resources:
  Public1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0889a44b331db0194
      KeyName: my-key-pair
      SecurityGroupIds:
        - !ImportValue VPC-SSHAccess
      SubnetId: !ImportValue VPC-PublicSubnet1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum -y install postgresql15

Outputs:
  Public1Ip:
    Description: Public Ip
    Value:
      Fn::GetAtt:
        - Public1
        - PublicIp
