Transform: AWS::Serverless-2016-10-31

Description: Deploys instances

Parameters:
  UserData:
    Type: String
    Default: |
      #!/bin/bash
      sudo yum -y update
      sudo yum -y install postgresql15
      curl https://raw.githubusercontent.com/edwmurph/configs/master/dotfiles/ec2-bashrc >> /home/ec2-user/.bashrc

Resources:
  Public1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08333bccc35d71140
      KeyName: my-key-pair
      SecurityGroupIds:
        - !ImportValue vpc-SSHAccess
      SubnetId: !ImportValue vpc-PublicSubnet1
      UserData:
        Fn::Base64: !Ref UserData

  # Private1:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.micro
  #     ImageId: ami-08333bccc35d71140
  #     KeyName: my-key-pair
  #     SecurityGroupIds:
  #       - !ImportValue vpc-SSHAccess
  #     SubnetId: !ImportValue vpc-PrivateSubnet1
  #     UserData:
  #       Fn::Base64: !Ref UserData

Outputs:
  Public1Ip:
    Description: Public Ip
    Value:
      Fn::GetAtt:
        - Public1
        - PublicIp
