---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      serviceAccountName: test
      containers:
        - name: echo
          image: ghcr.io/edwmurph/echo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::899305035647:role/test-pod-role
